#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in8,    indexHigh,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  encoderError,   sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightWheel2,   tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           flywheel4,     tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightWheel13,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           flywheel3,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftWheel2,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           flywheel1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           flywheel2,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftWheel13,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           indexer,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          intake,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(60)
#pragma userControlDuration(0)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

enum { VELOCITY_LONG = 182, VELOCITY_HOLD = 30, VELOCITY_PIPE = 130 }; //MAY NEED TO SWITCH BACK TO typedef and a name before the semicolon

bool tuneMode = false; //ONLY TRUE FOR PID TUNING

#warning "setLeftWheelSpeed"
void setLeftWheelSpeed ( int speed = 127 ) {
	motor[leftWheel13] = speed;
	motor[leftWheel2] = speed;
}

#warning "setRightWheelSpeed"
void setRightWheelSpeed ( int speed = 127 ) {
	motor[rightWheel13] = speed;
	motor[rightWheel2] = speed;
}

#warning "setWheelSpeed"
void setWheelSpeed ( int leftWheelSpeed = 127, int rightWheelSpeed = 127 ) {
	setLeftWheelSpeed(leftWheelSpeed);
	setRightWheelSpeed(rightWheelSpeed);
}

void setWheelSpeed ( int wheelSpeed = 127 ) {
	setWheelSpeed(wheelSpeed,wheelSpeed);
}

#warning "logDrive"
void logDrive () {
	int rawLeft, rawRight, outLeft, outRight;
	rawLeft = vexRT(Ch3);
	rawRight = vexRT(Ch2);

	outLeft = rawLeft*rawLeft/127;
	outRight = rawRight*rawRight/127;

	if(rawLeft<0)
		outLeft*=-1;
	if(rawRight<0)
		outRight*=-1;

	setWheelSpeed(outLeft,outRight);
}

bool lastUpButton=false;
bool lastDownButton=false;
bool currentUpButton;
bool currentDownButton;
int currentGoalVelocity=VELOCITY_LONG;
int currentVelocity;

float error=0;
float integral=0;
int output;
int velocities[5];
#warning "flywheelVelocity"
task flywheelVelocity(){
	int nextIndex=0;
	while(true){
		velocities[nextIndex]=getMotorVelocity(flywheel4);
		nextIndex++;
		if(nextIndex==5)
			nextIndex=0;
		delay(5);
	}
}

#warning "getFlywheelVelocity"
int getFlywheelVelocity(){
	int sum=0;
	for(int i=0;i<5;i++)
		sum = sum + velocities[i];
	return sum/5;
}

bool flywheelOn = false;
#warning "flywheelControl"
task flywheelControl(){
	flywheelOn = true;
	clearDebugStream();

	float kP=1.665;
	float kI=0.0025;
	int limit = 15;
	while(true){

		currentVelocity = getFlywheelVelocity();//might need work
		error = (currentGoalVelocity - currentVelocity);
		integral = integral + error;
		if(integral>(100/kI))
			integral = 100/kI;
		output = error*kP + integral*kI;
		if(output >25){
			if(output>motor[flywheel4]+limit){
				motor[flywheel4]=motor[flywheel4]+limit;
			}else if(output<motor[flywheel4]-limit){
				motor[flywheel4]=motor[flywheel4]-limit;
			}else{
				motor[flywheel4]=output;
			}
		}else if(output<0){
			motor[flywheel4]=0;
			//integral=0;
		}
		writeDebugStreamLine("Motors: %d, Error: %d, P: %d, I: %d Integral: %d", motor[flywheel1], error, error*kP, integral*kI, integral);
		delay(80);
	}
}

bool flywheelHold = false;
#warning "startFlywheel"
void startFlywheel (int targetVelocity) {
	currentGoalVelocity = targetVelocity;
	if(targetVelocity == (int) VELOCITY_HOLD) {
		motor[flywheel4] = VELOCITY_HOLD;
		stopTask(flywheelVelocity);
		stopTask(flywheelControl);
		flywheelHold = true;
	} else if(!flywheelOn || flywheelHold) {
		startTask(flywheelVelocity);
		startTask(flywheelControl);
		flywheelHold = false;
	}
}

bool autoIntake = false;
void startAutoFlywheel (int targetVelocity) {
	startFlywheel(targetVelocity);
	autoIntake = false;
}

#warning "stopFlywheel"
task stopFlywheel () {
	flywheelOn = false;
	autoIntake = false;
	stopTask(flywheelControl);
	while(motor[flywheel4]>0){
		motor[flywheel4] -= 1;
		delay(20);
	}
	stopTask(flywheelVelocity);
	stopTask(stopFlywheel);
}

#warning "autoLoad"
void autoLoad () {
	startFlywheel(VELOCITY_LONG);
	autoIntake = true;
}

int ballIndexerLimit = 2000;
int velocityTime = 400;
int velocityLimit = 23;
#warning "intakeControl"
task intakeControl () {
	while(true) {
		motor[intake]=(tuneMode+vexRT[Btn5U]-vexRT[Btn5D])*127;

		if(vexRT(Btn5U)||tuneMode) {
			if(SensorValue[indexHigh]>ballIndexerLimit) {
				motor[indexer] = (tuneMode+vexRT[Btn5U]-vexRT[Btn5D])*127;
			} else if (time1[T1]>velocityTime && (vexRT(Btn6U) || tuneMode) && (abs(currentGoalVelocity-currentVelocity)<velocityLimit)) {
				motor[indexer] = (tuneMode+vexRT[Btn5U]-vexRT[Btn5D])*127;
				delay(90);
				clearTimer(T1);
			} else {
				motor[indexer] = 0;
			}
		} else if(vexRT(Btn5D)) {
			motor[indexer] = (tuneMode+vexRT[Btn5U]-vexRT[Btn5D])*127;
		} else {
			motor[indexer] = 0;
		}
	}
		//if(SensorValue[indexHigh]>=ballIndexerLimit && (vexRT(Btn5U) || tuneMode)) {
		//	motor[indexer] = (tuneMode+vexRt[Btn5U]-vexRt[Btn5D])*127;
		//} else if(!vexRT(Btn5D) && time1[T1]<velocityTime && /*abs(currentGoalVelocity-currentVelocity)>velocityLimit &&*/ SensorValue[indexHigh]<ballIndexerLimit) {
		//	motor[indexer] = 0;
		//} else if((vexRT(Btn5U) && vexRT(Btn6U)) || tuneMode || autoIntake || vexRT(Btn5D)) {
		//	motor[indexer] = (tuneMode+vexRt[Btn5U]-vexRt[Btn5D])*127;
		//	if(time1[T1]>velocityTime+150) {
		//		clearTimer(T1);
		//	}
  //  } else {
		//	motor[indexer] = 0;
		//}
}

void testEncoder () {
	SensorValue[encoderError] = 0;
	startFlywheel(VELOCITY_LONG);
	delay(6000);
	if(motor[flywheel4] == 127)
		SensorValue[encoderError] = 1;
	else
		SensorValue[encoderError] = 0;
	startTask(stopFlywheel);
}

#warning "init"
void init() {
	slaveMotor(flywheel2,flywheel4);
	slaveMotor(flywheel3,flywheel4);
	slaveMotor(flywheel1,flywheel4);
	startTask(intakeControl);
}

void pre_auton() {
	bStopTasksBetweenModes = true;
}

task autonomous() {
	clearTimer(T2);
	startFlywheel(VELOCITY_LONG);
	while(time100[T1]<600) { delay(25); }
	startTask(stopFlywheel);
	//setWheelSpeed();
	//delay(1500);
	//setWheelSpeed(127,-127);
	//delay(400);
	//setWheelSpeed(-127);
	//startFlywheel(VELOCITY_LONG);
	//delay(1500);
	//setWheelSpeed(0);
}

task usercontrol() {
	init();

	while (true) {
		lastUpButton=currentUpButton;
		lastDownButton=currentDownButton;
		currentUpButton = (bool)vexRT[Btn5U];
		currentDownButton = (bool)vexRT[Btn5D];

		if(vexRT(Btn8R))
			startAutoFlywheel(VELOCITY_PIPE);

		else if(vexRT(Btn8D))
			startAutoFlywheel(VELOCITY_HOLD);

		else if(vexRT(Btn8L))
			startAutoFlywheel(VELOCITY_LONG);

		else if(vexRT(Btn8U))
			startTask(stopFlywheel);

		else if(vexRT(Btn7D))
			autoLoad();

		if(currentUpButton && !lastUpButton)
			currentGoalVelocity+=2;
		if(currentDownButton && !lastDownButton)
			currentGoalVelocity-=2;

		logDrive();
	}
}
