#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  outtake,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           flywheel1,     tmotorVex393HighSpeed_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           Intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Indexer,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           flywheel2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           flywheel3,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          flywheel4,     tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Enum for four differient flywheel states
typedef enum { FW_OFF = 0, FW_IDLE = 60, FW_ON = 80, FW_BANG = 127 } flywheelStates;

#warning "updateFlywheel"
int currentFlywheelState = FW_OFF;
int targetFlywheelState = FW_OFF;
int flywheelBangTime = 1000; //ms

task updateFlywheel () {
	if(abs(targetFlywheelState-motor[flywheel1]) > 5) {//threshold to set currentFlywheelState
		currentFlywheelState = targetFlywheelState;
	} else if(targetFlywheelState == FW_BANG && currentFlywheelState == FW_ON) {
		motor[flywheel1] = FW_BANG;
		wait1Msec(flywheelBangTime);
		motor[flywheel1] = FW_ON; //can also sub with updateFlywheel(FW_ON); as well
	}
	while (motor[flywheel1] < targetFlywheelState) {
		if(targetFlywheelState-motor[flywheel1] == 1)
			motor[flywheel1]+=1;
		else
			motor[flywheel1]+=2;
	}
	while (motor[flywheel1] > targetFlywheelState) {
		if(motor[flywheel1]-targetFlywheelState == 1)
			motor[flywheel1]-=1;
		else
			motor[flywheel1]-=2;
	}
}

void init() {
	slaveMotor(flywheel2,flywheel1);
	slaveMotor(flywheel3,flywheel1);
	slaveMotor(flywheel4,flywheel1);
	startTask(updateFlywheel);
}

task main () {
	init();
	while(true) {
		if(vexRT(Btn7U))
			targetFlywheelState = FW_IDLE;
		else if(vexRT(Btn7D))
			targetFlywheelState = FW_OFF;
		else if(vexRT(Btn7L))
			targetFlywheelState = FW_ON;
		else if(SensorValue[outtake])
			targetFlywheelState = FW_BANG;
	}
}
