#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	motor[intake] = (vexRT(Btn5U)-vexRT(Btn5D))*127;

}
